### ISSUE TITLE
Создать лендинг

### ISSUE THREAD

**Issue by kicumkicum** [teacher-army/teacher-army#8]
Структура примерно такая

```
::Логотип    ::Название    ::Меню

::Слоган
::Небольшой текст-первая удочка

::Основная задача
::Описание как    ::Картинка

::Кубики с кейсами или плюсами

::Ещё задача
::Описание как

::Вопросы и ответы

::Какое-то воодушевление
::Описание

::Какие-то плиточки

::Какой-то кейс
::Описание

::Отзыв

::Форма с заявкой или контакт
::Кнопка с телегой
```

Инфа
- https://tilda.education/articles-offer
- https://tilda.education/articles-how-to-write-text-for-landing

Макет - https://www.figma.com/file/08GN2pCOByIhIGY4hwPR5u/Source-file?node-id=50%3A4

**Comment by kicumkicum** [comment]
- Логотип - OO
- Название - Teacher Army
- Меню - TODO

- Слоган - Стал программистом? Пришло время становиться крутым!
- Небольшой текст - ууу

- Основная задача - Мы помогаем стать лучше
- Описание как - Мы собрали лучших людей индустрии, чтобы они могли научить вас лучшим практикам

- Кубики
  - Фронт
  - Бек
  - Архитектура
  - Паттерны

- Занятия с наставником дают невообразимый трамплин и вкачивают тебя с двойной скоростью
- Бла бла бла

**Comment by zeckson** [comment]
у меня кстати есть хороший верстальщик из академии, можем с ним поговорить

**Comment by kicumkicum** [comment]
У меня тоже) Думаю скоро Аня сможет взять его в работу
